name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Jest tests
      run: npm test
      env:
        CI: true  # Ensures test output is simplified for CI

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jest-results
        path: |
          coverage/
          test-results/

    # Prevent large file issues (like your earlier MongoDB binary)
    - name: Check for large files
      run: |
        echo "Checking for files >50MB..."
        find . -type f -size +50M ! -path "./node_modules/*" ! -path "./.git/*" || echo "No oversized files found"